// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type DeleteMeshTrafficPermissionRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// name of the MeshTrafficPermission
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (d *DeleteMeshTrafficPermissionRequest) GetMesh() string {
	if d == nil {
		return ""
	}
	return d.Mesh
}

func (d *DeleteMeshTrafficPermissionRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

type DeleteMeshTrafficPermissionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshTrafficPermissionDeleteSuccessResponse *shared.MeshTrafficPermissionDeleteSuccessResponse
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (d *DeleteMeshTrafficPermissionResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteMeshTrafficPermissionResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteMeshTrafficPermissionResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteMeshTrafficPermissionResponse) GetMeshTrafficPermissionDeleteSuccessResponse() *shared.MeshTrafficPermissionDeleteSuccessResponse {
	if d == nil {
		return nil
	}
	return d.MeshTrafficPermissionDeleteSuccessResponse
}

func (d *DeleteMeshTrafficPermissionResponse) GetNotFoundError() *shared.NotFoundError {
	if d == nil {
		return nil
	}
	return d.NotFoundError
}
