// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PutMeshTrustRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// name of the MeshTrust
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Put request
	MeshTrustItem shared.MeshTrustItemInput `request:"mediaType=application/json"`
}

func (o *PutMeshTrustRequest) GetMesh() string {
	if o == nil {
		return ""
	}
	return o.Mesh
}

func (o *PutMeshTrustRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PutMeshTrustRequest) GetMeshTrustItem() shared.MeshTrustItemInput {
	if o == nil {
		return shared.MeshTrustItemInput{}
	}
	return o.MeshTrustItem
}

type PutMeshTrustResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated
	MeshTrustCreateOrUpdateSuccessResponse *shared.MeshTrustCreateOrUpdateSuccessResponse
}

func (o *PutMeshTrustResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutMeshTrustResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutMeshTrustResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PutMeshTrustResponse) GetMeshTrustCreateOrUpdateSuccessResponse() *shared.MeshTrustCreateOrUpdateSuccessResponse {
	if o == nil {
		return nil
	}
	return o.MeshTrustCreateOrUpdateSuccessResponse
}
