// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PutMeshCircuitBreakerRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// name of the MeshCircuitBreaker
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Put request
	MeshCircuitBreakerItem shared.MeshCircuitBreakerItemInput `request:"mediaType=application/json"`
}

func (p *PutMeshCircuitBreakerRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PutMeshCircuitBreakerRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutMeshCircuitBreakerRequest) GetMeshCircuitBreakerItem() shared.MeshCircuitBreakerItemInput {
	if p == nil {
		return shared.MeshCircuitBreakerItemInput{}
	}
	return p.MeshCircuitBreakerItem
}

type PutMeshCircuitBreakerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated
	MeshCircuitBreakerCreateOrUpdateSuccessResponse *shared.MeshCircuitBreakerCreateOrUpdateSuccessResponse
}

func (p *PutMeshCircuitBreakerResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutMeshCircuitBreakerResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutMeshCircuitBreakerResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutMeshCircuitBreakerResponse) GetMeshCircuitBreakerCreateOrUpdateSuccessResponse() *shared.MeshCircuitBreakerCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshCircuitBreakerCreateOrUpdateSuccessResponse
}
