// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PutMeshRetryRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// name of the MeshRetry
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Put request
	MeshRetryItem shared.MeshRetryItemInput `request:"mediaType=application/json"`
}

func (p *PutMeshRetryRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PutMeshRetryRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutMeshRetryRequest) GetMeshRetryItem() shared.MeshRetryItemInput {
	if p == nil {
		return shared.MeshRetryItemInput{}
	}
	return p.MeshRetryItem
}

type PutMeshRetryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated
	MeshRetryCreateOrUpdateSuccessResponse *shared.MeshRetryCreateOrUpdateSuccessResponse
}

func (p *PutMeshRetryResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutMeshRetryResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutMeshRetryResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutMeshRetryResponse) GetMeshRetryCreateOrUpdateSuccessResponse() *shared.MeshRetryCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshRetryCreateOrUpdateSuccessResponse
}
