// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PutMeshHTTPRouteRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// name of the MeshHTTPRoute
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Put request
	MeshHTTPRouteItem shared.MeshHTTPRouteItemInput `request:"mediaType=application/json"`
}

func (p *PutMeshHTTPRouteRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PutMeshHTTPRouteRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutMeshHTTPRouteRequest) GetMeshHTTPRouteItem() shared.MeshHTTPRouteItemInput {
	if p == nil {
		return shared.MeshHTTPRouteItemInput{}
	}
	return p.MeshHTTPRouteItem
}

type PutMeshHTTPRouteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated
	MeshHTTPRouteCreateOrUpdateSuccessResponse *shared.MeshHTTPRouteCreateOrUpdateSuccessResponse
}

func (p *PutMeshHTTPRouteResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutMeshHTTPRouteResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutMeshHTTPRouteResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutMeshHTTPRouteResponse) GetMeshHTTPRouteCreateOrUpdateSuccessResponse() *shared.MeshHTTPRouteCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshHTTPRouteCreateOrUpdateSuccessResponse
}
