// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DataplaneList - List
type DataplaneList struct {
	Items []DataplaneItem `json:"items,omitempty"`
	// The total number of entities
	Total *float64 `json:"total,omitempty"`
	// URL to the next page
	Next *string `json:"next,omitempty"`
}

func (o *DataplaneList) GetItems() []DataplaneItem {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *DataplaneList) GetTotal() *float64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *DataplaneList) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}
