// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshHealthCheckList - List
type MeshHealthCheckList struct {
	Items []MeshHealthCheckItem `json:"items,omitempty"`
	// The total number of entities
	Total *float64 `json:"total,omitempty"`
	// URL to the next page
	Next *string `json:"next,omitempty"`
}

func (m *MeshHealthCheckList) GetItems() []MeshHealthCheckItem {
	if m == nil {
		return nil
	}
	return m.Items
}

func (m *MeshHealthCheckList) GetTotal() *float64 {
	if m == nil {
		return nil
	}
	return m.Total
}

func (m *MeshHealthCheckList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
