// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshRetryList - List
type MeshRetryList struct {
	Items []MeshRetryItem `json:"items,omitempty"`
	// The total number of entities
	Total *float64 `json:"total,omitempty"`
	// URL to the next page
	Next *string `json:"next,omitempty"`
}

func (m *MeshRetryList) GetItems() []MeshRetryItem {
	if m == nil {
		return nil
	}
	return m.Items
}

func (m *MeshRetryList) GetTotal() *float64 {
	if m == nil {
		return nil
	}
	return m.Total
}

func (m *MeshRetryList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
