// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshList - List
type MeshList struct {
	Items []MeshItem `json:"items,omitempty"`
	// The total number of entities
	Total *float64 `json:"total,omitempty"`
	// URL to the next page
	Next *string `json:"next,omitempty"`
}

func (m *MeshList) GetItems() []MeshItem {
	if m == nil {
		return nil
	}
	return m.Items
}

func (m *MeshList) GetTotal() *float64 {
	if m == nil {
		return nil
	}
	return m.Total
}

func (m *MeshList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
