// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Rule struct {
	Matchers []RuleMatcher `json:"matchers"`
	// The actual conf generated
	Conf   map[string]any `json:"conf"`
	Origin []Meta         `json:"origin"`
}

func (o *Rule) GetMatchers() []RuleMatcher {
	if o == nil {
		return []RuleMatcher{}
	}
	return o.Matchers
}

func (o *Rule) GetConf() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Conf
}

func (o *Rule) GetOrigin() []Meta {
	if o == nil {
		return []Meta{}
	}
	return o.Origin
}
