// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// RuleMatcher - A matcher to select which traffic this conf applies to
type RuleMatcher struct {
	// the key to match against
	Key string `json:"key"`
	// the value for the key to match against
	Value string `json:"value"`
	// whether we check on the absence of this key:value pair
	Not bool `json:"not"`
}

func (o *RuleMatcher) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *RuleMatcher) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *RuleMatcher) GetNot() bool {
	if o == nil {
		return false
	}
	return o.Not
}
