workflowVersion: 1.0.0
speakeasyVersion: 1.645.1
sources:
    kong-mesh:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/kong/kong/terraform-provider-kong-mesh
targets:
    terraform:
        target: terraform
        source: kong-mesh
