// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/Kong/shared-speakeasy/customtypes/kumalabels"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-kong-mesh/internal/provider/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshTraceResourceModel) RefreshFromSharedMeshTraceCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.MeshTraceCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshTraceResourceModel) RefreshFromSharedMeshTraceItem(ctx context.Context, resp *shared.MeshTraceItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		labelsValue, labelsDiags := types.MapValueFrom(ctx, types.StringType, resp.Labels)
		diags.Append(labelsDiags...)
		labelsValuable, labelsDiags := kumalabels.KumaLabelsMapType{MapType: types.MapType{ElemType: types.StringType}}.ValueFromMap(ctx, labelsValue)
		diags.Append(labelsDiags...)
		r.Labels, _ = labelsValuable.(kumalabels.KumaLabelsMapValue)
		r.Mesh = types.StringPointerValue(resp.Mesh)
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		if resp.Spec.Default == nil {
			r.Spec.Default = nil
		} else {
			r.Spec.Default = &tfTypes.MeshTraceItemDefault{}
			r.Spec.Default.Backends = []tfTypes.MeshTraceItemBackends{}

			for _, backendsItem := range resp.Spec.Default.Backends {
				var backends tfTypes.MeshTraceItemBackends

				if backendsItem.Datadog == nil {
					backends.Datadog = nil
				} else {
					backends.Datadog = &tfTypes.Datadog{}
					backends.Datadog.SplitService = types.BoolPointerValue(backendsItem.Datadog.SplitService)
					backends.Datadog.URL = types.StringValue(backendsItem.Datadog.URL)
				}
				if backendsItem.OpenTelemetry == nil {
					backends.OpenTelemetry = nil
				} else {
					backends.OpenTelemetry = &tfTypes.MeshTraceItemOpenTelemetry{}
					backends.OpenTelemetry.Endpoint = types.StringValue(backendsItem.OpenTelemetry.Endpoint)
				}
				backends.Type = types.StringValue(string(backendsItem.Type))
				if backendsItem.Zipkin == nil {
					backends.Zipkin = nil
				} else {
					backends.Zipkin = &tfTypes.Zipkin{}
					if backendsItem.Zipkin.APIVersion != nil {
						backends.Zipkin.APIVersion = types.StringValue(string(*backendsItem.Zipkin.APIVersion))
					} else {
						backends.Zipkin.APIVersion = types.StringNull()
					}
					backends.Zipkin.SharedSpanContext = types.BoolPointerValue(backendsItem.Zipkin.SharedSpanContext)
					backends.Zipkin.TraceId128bit = types.BoolPointerValue(backendsItem.Zipkin.TraceId128bit)
					backends.Zipkin.URL = types.StringValue(backendsItem.Zipkin.URL)
				}

				r.Spec.Default.Backends = append(r.Spec.Default.Backends, backends)
			}
			if resp.Spec.Default.Sampling == nil {
				r.Spec.Default.Sampling = nil
			} else {
				r.Spec.Default.Sampling = &tfTypes.Sampling{}
				if resp.Spec.Default.Sampling.Client != nil {
					r.Spec.Default.Sampling.Client = &tfTypes.Mode{}
					if resp.Spec.Default.Sampling.Client.Integer != nil {
						r.Spec.Default.Sampling.Client.Integer = types.Int64PointerValue(resp.Spec.Default.Sampling.Client.Integer)
					}
					if resp.Spec.Default.Sampling.Client.Str != nil {
						r.Spec.Default.Sampling.Client.Str = types.StringPointerValue(resp.Spec.Default.Sampling.Client.Str)
					}
				}
				if resp.Spec.Default.Sampling.Overall != nil {
					r.Spec.Default.Sampling.Overall = &tfTypes.Mode{}
					if resp.Spec.Default.Sampling.Overall.Integer != nil {
						r.Spec.Default.Sampling.Overall.Integer = types.Int64PointerValue(resp.Spec.Default.Sampling.Overall.Integer)
					}
					if resp.Spec.Default.Sampling.Overall.Str != nil {
						r.Spec.Default.Sampling.Overall.Str = types.StringPointerValue(resp.Spec.Default.Sampling.Overall.Str)
					}
				}
				if resp.Spec.Default.Sampling.Random != nil {
					r.Spec.Default.Sampling.Random = &tfTypes.Mode{}
					if resp.Spec.Default.Sampling.Random.Integer != nil {
						r.Spec.Default.Sampling.Random.Integer = types.Int64PointerValue(resp.Spec.Default.Sampling.Random.Integer)
					}
					if resp.Spec.Default.Sampling.Random.Str != nil {
						r.Spec.Default.Sampling.Random.Str = types.StringPointerValue(resp.Spec.Default.Sampling.Random.Str)
					}
				}
			}
			r.Spec.Default.Tags = []tfTypes.Tags{}

			for _, tagsItem := range resp.Spec.Default.Tags {
				var tags tfTypes.Tags

				if tagsItem.Header == nil {
					tags.Header = nil
				} else {
					tags.Header = &tfTypes.Header{}
					tags.Header.Default = types.StringPointerValue(tagsItem.Header.Default)
					tags.Header.Name = types.StringValue(tagsItem.Header.Name)
				}
				tags.Literal = types.StringPointerValue(tagsItem.Literal)
				tags.Name = types.StringValue(tagsItem.Name)

				r.Spec.Default.Tags = append(r.Spec.Default.Tags, tags)
			}
		}
		if resp.Spec.TargetRef == nil {
			r.Spec.TargetRef = nil
		} else {
			r.Spec.TargetRef = &tfTypes.MeshAccessLogItemTargetRef{}
			r.Spec.TargetRef.Kind = types.StringValue(string(resp.Spec.TargetRef.Kind))
			if len(resp.Spec.TargetRef.Labels) > 0 {
				r.Spec.TargetRef.Labels = make(map[string]types.String, len(resp.Spec.TargetRef.Labels))
				for key, value := range resp.Spec.TargetRef.Labels {
					r.Spec.TargetRef.Labels[key] = types.StringValue(value)
				}
			}
			r.Spec.TargetRef.Mesh = types.StringPointerValue(resp.Spec.TargetRef.Mesh)
			r.Spec.TargetRef.Name = types.StringPointerValue(resp.Spec.TargetRef.Name)
			r.Spec.TargetRef.Namespace = types.StringPointerValue(resp.Spec.TargetRef.Namespace)
			r.Spec.TargetRef.ProxyTypes = make([]types.String, 0, len(resp.Spec.TargetRef.ProxyTypes))
			for _, v := range resp.Spec.TargetRef.ProxyTypes {
				r.Spec.TargetRef.ProxyTypes = append(r.Spec.TargetRef.ProxyTypes, types.StringValue(string(v)))
			}
			r.Spec.TargetRef.SectionName = types.StringPointerValue(resp.Spec.TargetRef.SectionName)
			if len(resp.Spec.TargetRef.Tags) > 0 {
				r.Spec.TargetRef.Tags = make(map[string]types.String, len(resp.Spec.TargetRef.Tags))
				for key1, value1 := range resp.Spec.TargetRef.Tags {
					r.Spec.TargetRef.Tags[key1] = types.StringValue(value1)
				}
			}
		}
		r.Type = types.StringValue(string(resp.Type))
	}

	return diags
}

func (r *MeshTraceResourceModel) ToOperationsDeleteMeshTraceRequest(ctx context.Context) (*operations.DeleteMeshTraceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteMeshTraceRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshTraceResourceModel) ToOperationsGetMeshTraceRequest(ctx context.Context) (*operations.GetMeshTraceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.GetMeshTraceRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshTraceResourceModel) ToOperationsPutMeshTraceRequest(ctx context.Context) (*operations.PutMeshTraceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	meshTraceItem, meshTraceItemDiags := r.ToSharedMeshTraceItemInput(ctx)
	diags.Append(meshTraceItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutMeshTraceRequest{
		Mesh:          mesh,
		Name:          name,
		MeshTraceItem: *meshTraceItem,
	}

	return &out, diags
}

func (r *MeshTraceResourceModel) ToSharedMeshTraceItemInput(ctx context.Context) (*shared.MeshTraceItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	typeVar := shared.MeshTraceItemType(r.Type.ValueString())
	mesh := new(string)
	if !r.Mesh.IsUnknown() && !r.Mesh.IsNull() {
		*mesh = r.Mesh.ValueString()
	} else {
		mesh = nil
	}
	var name string
	name = r.Name.ValueString()

	var labels map[string]string
	if !r.Labels.IsUnknown() && !r.Labels.IsNull() {
		diags.Append(r.Labels.ElementsAs(ctx, &labels, true)...)
	}
	var defaultVar *shared.MeshTraceItemDefault
	if r.Spec.Default != nil {
		backends := make([]shared.MeshTraceItemBackends, 0, len(r.Spec.Default.Backends))
		for _, backendsItem := range r.Spec.Default.Backends {
			var datadog *shared.Datadog
			if backendsItem.Datadog != nil {
				splitService := new(bool)
				if !backendsItem.Datadog.SplitService.IsUnknown() && !backendsItem.Datadog.SplitService.IsNull() {
					*splitService = backendsItem.Datadog.SplitService.ValueBool()
				} else {
					splitService = nil
				}
				var url string
				url = backendsItem.Datadog.URL.ValueString()

				datadog = &shared.Datadog{
					SplitService: splitService,
					URL:          url,
				}
			}
			var openTelemetry *shared.MeshTraceItemOpenTelemetry
			if backendsItem.OpenTelemetry != nil {
				var endpoint string
				endpoint = backendsItem.OpenTelemetry.Endpoint.ValueString()

				openTelemetry = &shared.MeshTraceItemOpenTelemetry{
					Endpoint: endpoint,
				}
			}
			type1 := shared.MeshTraceItemSpecType(backendsItem.Type.ValueString())
			var zipkin *shared.Zipkin
			if backendsItem.Zipkin != nil {
				apiVersion := new(shared.APIVersion)
				if !backendsItem.Zipkin.APIVersion.IsUnknown() && !backendsItem.Zipkin.APIVersion.IsNull() {
					*apiVersion = shared.APIVersion(backendsItem.Zipkin.APIVersion.ValueString())
				} else {
					apiVersion = nil
				}
				sharedSpanContext := new(bool)
				if !backendsItem.Zipkin.SharedSpanContext.IsUnknown() && !backendsItem.Zipkin.SharedSpanContext.IsNull() {
					*sharedSpanContext = backendsItem.Zipkin.SharedSpanContext.ValueBool()
				} else {
					sharedSpanContext = nil
				}
				traceId128bit := new(bool)
				if !backendsItem.Zipkin.TraceId128bit.IsUnknown() && !backendsItem.Zipkin.TraceId128bit.IsNull() {
					*traceId128bit = backendsItem.Zipkin.TraceId128bit.ValueBool()
				} else {
					traceId128bit = nil
				}
				var url1 string
				url1 = backendsItem.Zipkin.URL.ValueString()

				zipkin = &shared.Zipkin{
					APIVersion:        apiVersion,
					SharedSpanContext: sharedSpanContext,
					TraceId128bit:     traceId128bit,
					URL:               url1,
				}
			}
			backends = append(backends, shared.MeshTraceItemBackends{
				Datadog:       datadog,
				OpenTelemetry: openTelemetry,
				Type:          type1,
				Zipkin:        zipkin,
			})
		}
		var sampling *shared.Sampling
		if r.Spec.Default.Sampling != nil {
			var client *shared.Client
			if r.Spec.Default.Sampling.Client != nil {
				integer := new(int64)
				if !r.Spec.Default.Sampling.Client.Integer.IsUnknown() && !r.Spec.Default.Sampling.Client.Integer.IsNull() {
					*integer = r.Spec.Default.Sampling.Client.Integer.ValueInt64()
				} else {
					integer = nil
				}
				if integer != nil {
					client = &shared.Client{
						Integer: integer,
					}
				}
				str := new(string)
				if !r.Spec.Default.Sampling.Client.Str.IsUnknown() && !r.Spec.Default.Sampling.Client.Str.IsNull() {
					*str = r.Spec.Default.Sampling.Client.Str.ValueString()
				} else {
					str = nil
				}
				if str != nil {
					client = &shared.Client{
						Str: str,
					}
				}
			}
			var overall *shared.Overall
			if r.Spec.Default.Sampling.Overall != nil {
				integer1 := new(int64)
				if !r.Spec.Default.Sampling.Overall.Integer.IsUnknown() && !r.Spec.Default.Sampling.Overall.Integer.IsNull() {
					*integer1 = r.Spec.Default.Sampling.Overall.Integer.ValueInt64()
				} else {
					integer1 = nil
				}
				if integer1 != nil {
					overall = &shared.Overall{
						Integer: integer1,
					}
				}
				str1 := new(string)
				if !r.Spec.Default.Sampling.Overall.Str.IsUnknown() && !r.Spec.Default.Sampling.Overall.Str.IsNull() {
					*str1 = r.Spec.Default.Sampling.Overall.Str.ValueString()
				} else {
					str1 = nil
				}
				if str1 != nil {
					overall = &shared.Overall{
						Str: str1,
					}
				}
			}
			var random *shared.Random
			if r.Spec.Default.Sampling.Random != nil {
				integer2 := new(int64)
				if !r.Spec.Default.Sampling.Random.Integer.IsUnknown() && !r.Spec.Default.Sampling.Random.Integer.IsNull() {
					*integer2 = r.Spec.Default.Sampling.Random.Integer.ValueInt64()
				} else {
					integer2 = nil
				}
				if integer2 != nil {
					random = &shared.Random{
						Integer: integer2,
					}
				}
				str2 := new(string)
				if !r.Spec.Default.Sampling.Random.Str.IsUnknown() && !r.Spec.Default.Sampling.Random.Str.IsNull() {
					*str2 = r.Spec.Default.Sampling.Random.Str.ValueString()
				} else {
					str2 = nil
				}
				if str2 != nil {
					random = &shared.Random{
						Str: str2,
					}
				}
			}
			sampling = &shared.Sampling{
				Client:  client,
				Overall: overall,
				Random:  random,
			}
		}
		tags := make([]shared.Tags, 0, len(r.Spec.Default.Tags))
		for _, tagsItem := range r.Spec.Default.Tags {
			var header *shared.Header
			if tagsItem.Header != nil {
				defaultVar1 := new(string)
				if !tagsItem.Header.Default.IsUnknown() && !tagsItem.Header.Default.IsNull() {
					*defaultVar1 = tagsItem.Header.Default.ValueString()
				} else {
					defaultVar1 = nil
				}
				var name1 string
				name1 = tagsItem.Header.Name.ValueString()

				header = &shared.Header{
					Default: defaultVar1,
					Name:    name1,
				}
			}
			literal := new(string)
			if !tagsItem.Literal.IsUnknown() && !tagsItem.Literal.IsNull() {
				*literal = tagsItem.Literal.ValueString()
			} else {
				literal = nil
			}
			var name2 string
			name2 = tagsItem.Name.ValueString()

			tags = append(tags, shared.Tags{
				Header:  header,
				Literal: literal,
				Name:    name2,
			})
		}
		defaultVar = &shared.MeshTraceItemDefault{
			Backends: backends,
			Sampling: sampling,
			Tags:     tags,
		}
	}
	var targetRef *shared.MeshTraceItemTargetRef
	if r.Spec.TargetRef != nil {
		kind := shared.MeshTraceItemKind(r.Spec.TargetRef.Kind.ValueString())
		labels1 := make(map[string]string)
		for labelsKey, labelsValue := range r.Spec.TargetRef.Labels {
			var labelsInst string
			labelsInst = labelsValue.ValueString()

			labels1[labelsKey] = labelsInst
		}
		mesh1 := new(string)
		if !r.Spec.TargetRef.Mesh.IsUnknown() && !r.Spec.TargetRef.Mesh.IsNull() {
			*mesh1 = r.Spec.TargetRef.Mesh.ValueString()
		} else {
			mesh1 = nil
		}
		name3 := new(string)
		if !r.Spec.TargetRef.Name.IsUnknown() && !r.Spec.TargetRef.Name.IsNull() {
			*name3 = r.Spec.TargetRef.Name.ValueString()
		} else {
			name3 = nil
		}
		namespace := new(string)
		if !r.Spec.TargetRef.Namespace.IsUnknown() && !r.Spec.TargetRef.Namespace.IsNull() {
			*namespace = r.Spec.TargetRef.Namespace.ValueString()
		} else {
			namespace = nil
		}
		proxyTypes := make([]shared.MeshTraceItemProxyTypes, 0, len(r.Spec.TargetRef.ProxyTypes))
		for _, proxyTypesItem := range r.Spec.TargetRef.ProxyTypes {
			proxyTypes = append(proxyTypes, shared.MeshTraceItemProxyTypes(proxyTypesItem.ValueString()))
		}
		sectionName := new(string)
		if !r.Spec.TargetRef.SectionName.IsUnknown() && !r.Spec.TargetRef.SectionName.IsNull() {
			*sectionName = r.Spec.TargetRef.SectionName.ValueString()
		} else {
			sectionName = nil
		}
		tags1 := make(map[string]string)
		for tagsKey, tagsValue := range r.Spec.TargetRef.Tags {
			var tagsInst string
			tagsInst = tagsValue.ValueString()

			tags1[tagsKey] = tagsInst
		}
		targetRef = &shared.MeshTraceItemTargetRef{
			Kind:        kind,
			Labels:      labels1,
			Mesh:        mesh1,
			Name:        name3,
			Namespace:   namespace,
			ProxyTypes:  proxyTypes,
			SectionName: sectionName,
			Tags:        tags1,
		}
	}
	spec := shared.MeshTraceItemSpec{
		Default:   defaultVar,
		TargetRef: targetRef,
	}
	out := shared.MeshTraceItemInput{
		Type:   typeVar,
		Mesh:   mesh,
		Name:   name,
		Labels: labels,
		Spec:   spec,
	}

	return &out, diags
}
