// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-kong-mesh/internal/provider/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshWorkloadResourceModel) RefreshFromSharedWorkloadCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.WorkloadCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshWorkloadResourceModel) RefreshFromSharedWorkloadItem(ctx context.Context, resp *shared.WorkloadItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		r.Kri = types.StringPointerValue(resp.Kri)
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key, value := range resp.Labels {
				r.Labels[key] = types.StringValue(value)
			}
		}
		r.Mesh = types.StringPointerValue(resp.Mesh)
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		r.Spec = &tfTypes.Options{}
		if resp.Status == nil {
			r.Status = nil
		} else {
			r.Status = &tfTypes.WorkloadItemStatus{}
			if resp.Status.DataplaneProxies == nil {
				r.Status.DataplaneProxies = nil
			} else {
				r.Status.DataplaneProxies = &tfTypes.WorkloadItemDataplaneProxies{}
				r.Status.DataplaneProxies.Connected = types.Int32Value(int32(resp.Status.DataplaneProxies.Connected))
				r.Status.DataplaneProxies.Healthy = types.Int32Value(int32(resp.Status.DataplaneProxies.Healthy))
				r.Status.DataplaneProxies.Total = types.Int32Value(int32(resp.Status.DataplaneProxies.Total))
			}
		}
		r.Type = types.StringValue(string(resp.Type))
	}

	return diags
}

func (r *MeshWorkloadResourceModel) ToOperationsDeleteWorkloadRequest(ctx context.Context) (*operations.DeleteWorkloadRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteWorkloadRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshWorkloadResourceModel) ToOperationsGetWorkloadRequest(ctx context.Context) (*operations.GetWorkloadRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.GetWorkloadRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshWorkloadResourceModel) ToOperationsPutWorkloadRequest(ctx context.Context) (*operations.PutWorkloadRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	workloadItem, workloadItemDiags := r.ToSharedWorkloadItemInput(ctx)
	diags.Append(workloadItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutWorkloadRequest{
		Mesh:         mesh,
		Name:         name,
		WorkloadItem: *workloadItem,
	}

	return &out, diags
}

func (r *MeshWorkloadResourceModel) ToSharedWorkloadItemInput(ctx context.Context) (*shared.WorkloadItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	typeVar := shared.WorkloadItemType(r.Type.ValueString())
	mesh := new(string)
	if !r.Mesh.IsUnknown() && !r.Mesh.IsNull() {
		*mesh = r.Mesh.ValueString()
	} else {
		mesh = nil
	}
	var name string
	name = r.Name.ValueString()

	labels := make(map[string]string)
	for labelsKey := range r.Labels {
		var labelsInst string
		labelsInst = r.Labels[labelsKey].ValueString()

		labels[labelsKey] = labelsInst
	}
	spec := shared.WorkloadItemSpec{}
	out := shared.WorkloadItemInput{
		Type:   typeVar,
		Mesh:   mesh,
		Name:   name,
		Labels: labels,
		Spec:   spec,
	}

	return &out, diags
}
