// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/Kong/shared-speakeasy/customtypes/kumalabels"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-kong-mesh/internal/provider/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshHealthCheckResourceModel) RefreshFromSharedMeshHealthCheckCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.MeshHealthCheckCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshHealthCheckResourceModel) RefreshFromSharedMeshHealthCheckItem(ctx context.Context, resp *shared.MeshHealthCheckItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		r.Kri = types.StringPointerValue(resp.Kri)
		labelsValue, labelsDiags := types.MapValueFrom(ctx, types.StringType, resp.Labels)
		diags.Append(labelsDiags...)
		labelsValuable, labelsDiags := kumalabels.KumaLabelsMapType{MapType: types.MapType{ElemType: types.StringType}}.ValueFromMap(ctx, labelsValue)
		diags.Append(labelsDiags...)
		r.Labels, _ = labelsValuable.(kumalabels.KumaLabelsMapValue)
		r.Mesh = types.StringPointerValue(resp.Mesh)
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		r.Spec = &tfTypes.MeshHealthCheckItemSpec{}
		if resp.Spec.TargetRef == nil {
			r.Spec.TargetRef = nil
		} else {
			r.Spec.TargetRef = &tfTypes.MeshAccessLogItemTargetRef{}
			r.Spec.TargetRef.Kind = types.StringValue(string(resp.Spec.TargetRef.Kind))
			if len(resp.Spec.TargetRef.Labels) > 0 {
				r.Spec.TargetRef.Labels = make(map[string]types.String, len(resp.Spec.TargetRef.Labels))
				for key, value := range resp.Spec.TargetRef.Labels {
					r.Spec.TargetRef.Labels[key] = types.StringValue(value)
				}
			}
			r.Spec.TargetRef.Mesh = types.StringPointerValue(resp.Spec.TargetRef.Mesh)
			r.Spec.TargetRef.Name = types.StringPointerValue(resp.Spec.TargetRef.Name)
			r.Spec.TargetRef.Namespace = types.StringPointerValue(resp.Spec.TargetRef.Namespace)
			r.Spec.TargetRef.ProxyTypes = make([]types.String, 0, len(resp.Spec.TargetRef.ProxyTypes))
			for _, v := range resp.Spec.TargetRef.ProxyTypes {
				r.Spec.TargetRef.ProxyTypes = append(r.Spec.TargetRef.ProxyTypes, types.StringValue(string(v)))
			}
			r.Spec.TargetRef.SectionName = types.StringPointerValue(resp.Spec.TargetRef.SectionName)
			if len(resp.Spec.TargetRef.Tags) > 0 {
				r.Spec.TargetRef.Tags = make(map[string]types.String, len(resp.Spec.TargetRef.Tags))
				for key1, value1 := range resp.Spec.TargetRef.Tags {
					r.Spec.TargetRef.Tags[key1] = types.StringValue(value1)
				}
			}
		}
		r.Spec.To = []tfTypes.MeshHealthCheckItemTo{}

		for _, toItem := range resp.Spec.To {
			var to tfTypes.MeshHealthCheckItemTo

			if toItem.Default == nil {
				to.Default = nil
			} else {
				to.Default = &tfTypes.MeshHealthCheckItemDefault{}
				to.Default.AlwaysLogHealthCheckFailures = types.BoolPointerValue(toItem.Default.AlwaysLogHealthCheckFailures)
				to.Default.EventLogPath = types.StringPointerValue(toItem.Default.EventLogPath)
				to.Default.FailTrafficOnPanic = types.BoolPointerValue(toItem.Default.FailTrafficOnPanic)
				if toItem.Default.Grpc == nil {
					to.Default.Grpc = nil
				} else {
					to.Default.Grpc = &tfTypes.Grpc{}
					to.Default.Grpc.Authority = types.StringPointerValue(toItem.Default.Grpc.Authority)
					to.Default.Grpc.Disabled = types.BoolPointerValue(toItem.Default.Grpc.Disabled)
					to.Default.Grpc.ServiceName = types.StringPointerValue(toItem.Default.Grpc.ServiceName)
				}
				if toItem.Default.HealthyPanicThreshold != nil {
					to.Default.HealthyPanicThreshold = &tfTypes.Mode{}
					if toItem.Default.HealthyPanicThreshold.Integer != nil {
						to.Default.HealthyPanicThreshold.Integer = types.Int64PointerValue(toItem.Default.HealthyPanicThreshold.Integer)
					}
					if toItem.Default.HealthyPanicThreshold.Str != nil {
						to.Default.HealthyPanicThreshold.Str = types.StringPointerValue(toItem.Default.HealthyPanicThreshold.Str)
					}
				}
				to.Default.HealthyThreshold = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(toItem.Default.HealthyThreshold))
				if toItem.Default.HTTP == nil {
					to.Default.HTTP = nil
				} else {
					to.Default.HTTP = &tfTypes.MeshHealthCheckItemHTTP{}
					to.Default.HTTP.Disabled = types.BoolPointerValue(toItem.Default.HTTP.Disabled)
					to.Default.HTTP.ExpectedStatuses = make([]types.Int64, 0, len(toItem.Default.HTTP.ExpectedStatuses))
					for _, v := range toItem.Default.HTTP.ExpectedStatuses {
						to.Default.HTTP.ExpectedStatuses = append(to.Default.HTTP.ExpectedStatuses, types.Int64Value(v))
					}
					to.Default.HTTP.Path = types.StringPointerValue(toItem.Default.HTTP.Path)
					if toItem.Default.HTTP.RequestHeadersToAdd == nil {
						to.Default.HTTP.RequestHeadersToAdd = nil
					} else {
						to.Default.HTTP.RequestHeadersToAdd = &tfTypes.MeshGlobalRateLimitItemHeaders{}
						to.Default.HTTP.RequestHeadersToAdd.Add = []tfTypes.MeshGlobalRateLimitItemAdd{}

						for _, addItem := range toItem.Default.HTTP.RequestHeadersToAdd.Add {
							var add tfTypes.MeshGlobalRateLimitItemAdd

							add.Name = types.StringValue(addItem.Name)
							add.Value = types.StringValue(addItem.Value)

							to.Default.HTTP.RequestHeadersToAdd.Add = append(to.Default.HTTP.RequestHeadersToAdd.Add, add)
						}
						to.Default.HTTP.RequestHeadersToAdd.Set = []tfTypes.MeshGlobalRateLimitItemAdd{}

						for _, setItem := range toItem.Default.HTTP.RequestHeadersToAdd.Set {
							var set tfTypes.MeshGlobalRateLimitItemAdd

							set.Name = types.StringValue(setItem.Name)
							set.Value = types.StringValue(setItem.Value)

							to.Default.HTTP.RequestHeadersToAdd.Set = append(to.Default.HTTP.RequestHeadersToAdd.Set, set)
						}
					}
				}
				to.Default.InitialJitter = types.StringPointerValue(toItem.Default.InitialJitter)
				to.Default.Interval = types.StringPointerValue(toItem.Default.Interval)
				to.Default.IntervalJitter = types.StringPointerValue(toItem.Default.IntervalJitter)
				to.Default.IntervalJitterPercent = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(toItem.Default.IntervalJitterPercent))
				to.Default.NoTrafficInterval = types.StringPointerValue(toItem.Default.NoTrafficInterval)
				to.Default.ReuseConnection = types.BoolPointerValue(toItem.Default.ReuseConnection)
				if toItem.Default.TCP == nil {
					to.Default.TCP = nil
				} else {
					to.Default.TCP = &tfTypes.TCP{}
					to.Default.TCP.Disabled = types.BoolPointerValue(toItem.Default.TCP.Disabled)
					to.Default.TCP.Receive = make([]types.String, 0, len(toItem.Default.TCP.Receive))
					for _, v := range toItem.Default.TCP.Receive {
						to.Default.TCP.Receive = append(to.Default.TCP.Receive, types.StringValue(v))
					}
					to.Default.TCP.Send = types.StringPointerValue(toItem.Default.TCP.Send)
				}
				to.Default.Timeout = types.StringPointerValue(toItem.Default.Timeout)
				to.Default.UnhealthyThreshold = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(toItem.Default.UnhealthyThreshold))
			}
			to.TargetRef = &tfTypes.MeshAccessLogItemTargetRef{}
			to.TargetRef.Kind = types.StringValue(string(toItem.TargetRef.Kind))
			if len(toItem.TargetRef.Labels) > 0 {
				to.TargetRef.Labels = make(map[string]types.String, len(toItem.TargetRef.Labels))
				for key2, value2 := range toItem.TargetRef.Labels {
					to.TargetRef.Labels[key2] = types.StringValue(value2)
				}
			}
			to.TargetRef.Mesh = types.StringPointerValue(toItem.TargetRef.Mesh)
			to.TargetRef.Name = types.StringPointerValue(toItem.TargetRef.Name)
			to.TargetRef.Namespace = types.StringPointerValue(toItem.TargetRef.Namespace)
			to.TargetRef.ProxyTypes = make([]types.String, 0, len(toItem.TargetRef.ProxyTypes))
			for _, v := range toItem.TargetRef.ProxyTypes {
				to.TargetRef.ProxyTypes = append(to.TargetRef.ProxyTypes, types.StringValue(string(v)))
			}
			to.TargetRef.SectionName = types.StringPointerValue(toItem.TargetRef.SectionName)
			if len(toItem.TargetRef.Tags) > 0 {
				to.TargetRef.Tags = make(map[string]types.String, len(toItem.TargetRef.Tags))
				for key3, value3 := range toItem.TargetRef.Tags {
					to.TargetRef.Tags[key3] = types.StringValue(value3)
				}
			}

			r.Spec.To = append(r.Spec.To, to)
		}
		r.Type = types.StringValue(string(resp.Type))
	}

	return diags
}

func (r *MeshHealthCheckResourceModel) ToOperationsDeleteMeshHealthCheckRequest(ctx context.Context) (*operations.DeleteMeshHealthCheckRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteMeshHealthCheckRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshHealthCheckResourceModel) ToOperationsGetMeshHealthCheckRequest(ctx context.Context) (*operations.GetMeshHealthCheckRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.GetMeshHealthCheckRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshHealthCheckResourceModel) ToOperationsPutMeshHealthCheckRequest(ctx context.Context) (*operations.PutMeshHealthCheckRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	meshHealthCheckItem, meshHealthCheckItemDiags := r.ToSharedMeshHealthCheckItemInput(ctx)
	diags.Append(meshHealthCheckItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutMeshHealthCheckRequest{
		Mesh:                mesh,
		Name:                name,
		MeshHealthCheckItem: *meshHealthCheckItem,
	}

	return &out, diags
}

func (r *MeshHealthCheckResourceModel) ToSharedMeshHealthCheckItemInput(ctx context.Context) (*shared.MeshHealthCheckItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	typeVar := shared.MeshHealthCheckItemType(r.Type.ValueString())
	mesh := new(string)
	if !r.Mesh.IsUnknown() && !r.Mesh.IsNull() {
		*mesh = r.Mesh.ValueString()
	} else {
		mesh = nil
	}
	var name string
	name = r.Name.ValueString()

	var labels map[string]string
	if !r.Labels.IsUnknown() && !r.Labels.IsNull() {
		diags.Append(r.Labels.ElementsAs(ctx, &labels, true)...)
	}
	var targetRef *shared.MeshHealthCheckItemTargetRef
	if r.Spec.TargetRef != nil {
		kind := shared.MeshHealthCheckItemKind(r.Spec.TargetRef.Kind.ValueString())
		labels1 := make(map[string]string)
		for labelsKey := range r.Spec.TargetRef.Labels {
			var labelsInst string
			labelsInst = r.Spec.TargetRef.Labels[labelsKey].ValueString()

			labels1[labelsKey] = labelsInst
		}
		mesh1 := new(string)
		if !r.Spec.TargetRef.Mesh.IsUnknown() && !r.Spec.TargetRef.Mesh.IsNull() {
			*mesh1 = r.Spec.TargetRef.Mesh.ValueString()
		} else {
			mesh1 = nil
		}
		name1 := new(string)
		if !r.Spec.TargetRef.Name.IsUnknown() && !r.Spec.TargetRef.Name.IsNull() {
			*name1 = r.Spec.TargetRef.Name.ValueString()
		} else {
			name1 = nil
		}
		namespace := new(string)
		if !r.Spec.TargetRef.Namespace.IsUnknown() && !r.Spec.TargetRef.Namespace.IsNull() {
			*namespace = r.Spec.TargetRef.Namespace.ValueString()
		} else {
			namespace = nil
		}
		proxyTypes := make([]shared.MeshHealthCheckItemProxyTypes, 0, len(r.Spec.TargetRef.ProxyTypes))
		for _, proxyTypesItem := range r.Spec.TargetRef.ProxyTypes {
			proxyTypes = append(proxyTypes, shared.MeshHealthCheckItemProxyTypes(proxyTypesItem.ValueString()))
		}
		sectionName := new(string)
		if !r.Spec.TargetRef.SectionName.IsUnknown() && !r.Spec.TargetRef.SectionName.IsNull() {
			*sectionName = r.Spec.TargetRef.SectionName.ValueString()
		} else {
			sectionName = nil
		}
		tags := make(map[string]string)
		for tagsKey := range r.Spec.TargetRef.Tags {
			var tagsInst string
			tagsInst = r.Spec.TargetRef.Tags[tagsKey].ValueString()

			tags[tagsKey] = tagsInst
		}
		targetRef = &shared.MeshHealthCheckItemTargetRef{
			Kind:        kind,
			Labels:      labels1,
			Mesh:        mesh1,
			Name:        name1,
			Namespace:   namespace,
			ProxyTypes:  proxyTypes,
			SectionName: sectionName,
			Tags:        tags,
		}
	}
	to := make([]shared.MeshHealthCheckItemTo, 0, len(r.Spec.To))
	for toIndex := range r.Spec.To {
		var defaultVar *shared.MeshHealthCheckItemDefault
		if r.Spec.To[toIndex].Default != nil {
			alwaysLogHealthCheckFailures := new(bool)
			if !r.Spec.To[toIndex].Default.AlwaysLogHealthCheckFailures.IsUnknown() && !r.Spec.To[toIndex].Default.AlwaysLogHealthCheckFailures.IsNull() {
				*alwaysLogHealthCheckFailures = r.Spec.To[toIndex].Default.AlwaysLogHealthCheckFailures.ValueBool()
			} else {
				alwaysLogHealthCheckFailures = nil
			}
			eventLogPath := new(string)
			if !r.Spec.To[toIndex].Default.EventLogPath.IsUnknown() && !r.Spec.To[toIndex].Default.EventLogPath.IsNull() {
				*eventLogPath = r.Spec.To[toIndex].Default.EventLogPath.ValueString()
			} else {
				eventLogPath = nil
			}
			failTrafficOnPanic := new(bool)
			if !r.Spec.To[toIndex].Default.FailTrafficOnPanic.IsUnknown() && !r.Spec.To[toIndex].Default.FailTrafficOnPanic.IsNull() {
				*failTrafficOnPanic = r.Spec.To[toIndex].Default.FailTrafficOnPanic.ValueBool()
			} else {
				failTrafficOnPanic = nil
			}
			var grpc *shared.Grpc
			if r.Spec.To[toIndex].Default.Grpc != nil {
				authority := new(string)
				if !r.Spec.To[toIndex].Default.Grpc.Authority.IsUnknown() && !r.Spec.To[toIndex].Default.Grpc.Authority.IsNull() {
					*authority = r.Spec.To[toIndex].Default.Grpc.Authority.ValueString()
				} else {
					authority = nil
				}
				disabled := new(bool)
				if !r.Spec.To[toIndex].Default.Grpc.Disabled.IsUnknown() && !r.Spec.To[toIndex].Default.Grpc.Disabled.IsNull() {
					*disabled = r.Spec.To[toIndex].Default.Grpc.Disabled.ValueBool()
				} else {
					disabled = nil
				}
				serviceName := new(string)
				if !r.Spec.To[toIndex].Default.Grpc.ServiceName.IsUnknown() && !r.Spec.To[toIndex].Default.Grpc.ServiceName.IsNull() {
					*serviceName = r.Spec.To[toIndex].Default.Grpc.ServiceName.ValueString()
				} else {
					serviceName = nil
				}
				grpc = &shared.Grpc{
					Authority:   authority,
					Disabled:    disabled,
					ServiceName: serviceName,
				}
			}
			var healthyPanicThreshold *shared.HealthyPanicThreshold
			if r.Spec.To[toIndex].Default.HealthyPanicThreshold != nil {
				integer := new(int64)
				if !r.Spec.To[toIndex].Default.HealthyPanicThreshold.Integer.IsUnknown() && !r.Spec.To[toIndex].Default.HealthyPanicThreshold.Integer.IsNull() {
					*integer = r.Spec.To[toIndex].Default.HealthyPanicThreshold.Integer.ValueInt64()
				} else {
					integer = nil
				}
				if integer != nil {
					healthyPanicThreshold = &shared.HealthyPanicThreshold{
						Integer: integer,
					}
				}
				str := new(string)
				if !r.Spec.To[toIndex].Default.HealthyPanicThreshold.Str.IsUnknown() && !r.Spec.To[toIndex].Default.HealthyPanicThreshold.Str.IsNull() {
					*str = r.Spec.To[toIndex].Default.HealthyPanicThreshold.Str.ValueString()
				} else {
					str = nil
				}
				if str != nil {
					healthyPanicThreshold = &shared.HealthyPanicThreshold{
						Str: str,
					}
				}
			}
			healthyThreshold := new(int)
			if !r.Spec.To[toIndex].Default.HealthyThreshold.IsUnknown() && !r.Spec.To[toIndex].Default.HealthyThreshold.IsNull() {
				*healthyThreshold = int(r.Spec.To[toIndex].Default.HealthyThreshold.ValueInt32())
			} else {
				healthyThreshold = nil
			}
			var http *shared.MeshHealthCheckItemHTTP
			if r.Spec.To[toIndex].Default.HTTP != nil {
				disabled1 := new(bool)
				if !r.Spec.To[toIndex].Default.HTTP.Disabled.IsUnknown() && !r.Spec.To[toIndex].Default.HTTP.Disabled.IsNull() {
					*disabled1 = r.Spec.To[toIndex].Default.HTTP.Disabled.ValueBool()
				} else {
					disabled1 = nil
				}
				expectedStatuses := make([]int64, 0, len(r.Spec.To[toIndex].Default.HTTP.ExpectedStatuses))
				for expectedStatusesIndex := range r.Spec.To[toIndex].Default.HTTP.ExpectedStatuses {
					expectedStatuses = append(expectedStatuses, r.Spec.To[toIndex].Default.HTTP.ExpectedStatuses[expectedStatusesIndex].ValueInt64())
				}
				path := new(string)
				if !r.Spec.To[toIndex].Default.HTTP.Path.IsUnknown() && !r.Spec.To[toIndex].Default.HTTP.Path.IsNull() {
					*path = r.Spec.To[toIndex].Default.HTTP.Path.ValueString()
				} else {
					path = nil
				}
				var requestHeadersToAdd *shared.RequestHeadersToAdd
				if r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd != nil {
					add := make([]shared.Add, 0, len(r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Add))
					for addIndex := range r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Add {
						var name2 string
						name2 = r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Add[addIndex].Name.ValueString()

						var value string
						value = r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Add[addIndex].Value.ValueString()

						add = append(add, shared.Add{
							Name:  name2,
							Value: value,
						})
					}
					set := make([]shared.Set, 0, len(r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Set))
					for setIndex := range r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Set {
						var name3 string
						name3 = r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Set[setIndex].Name.ValueString()

						var value1 string
						value1 = r.Spec.To[toIndex].Default.HTTP.RequestHeadersToAdd.Set[setIndex].Value.ValueString()

						set = append(set, shared.Set{
							Name:  name3,
							Value: value1,
						})
					}
					requestHeadersToAdd = &shared.RequestHeadersToAdd{
						Add: add,
						Set: set,
					}
				}
				http = &shared.MeshHealthCheckItemHTTP{
					Disabled:            disabled1,
					ExpectedStatuses:    expectedStatuses,
					Path:                path,
					RequestHeadersToAdd: requestHeadersToAdd,
				}
			}
			initialJitter := new(string)
			if !r.Spec.To[toIndex].Default.InitialJitter.IsUnknown() && !r.Spec.To[toIndex].Default.InitialJitter.IsNull() {
				*initialJitter = r.Spec.To[toIndex].Default.InitialJitter.ValueString()
			} else {
				initialJitter = nil
			}
			interval := new(string)
			if !r.Spec.To[toIndex].Default.Interval.IsUnknown() && !r.Spec.To[toIndex].Default.Interval.IsNull() {
				*interval = r.Spec.To[toIndex].Default.Interval.ValueString()
			} else {
				interval = nil
			}
			intervalJitter := new(string)
			if !r.Spec.To[toIndex].Default.IntervalJitter.IsUnknown() && !r.Spec.To[toIndex].Default.IntervalJitter.IsNull() {
				*intervalJitter = r.Spec.To[toIndex].Default.IntervalJitter.ValueString()
			} else {
				intervalJitter = nil
			}
			intervalJitterPercent := new(int)
			if !r.Spec.To[toIndex].Default.IntervalJitterPercent.IsUnknown() && !r.Spec.To[toIndex].Default.IntervalJitterPercent.IsNull() {
				*intervalJitterPercent = int(r.Spec.To[toIndex].Default.IntervalJitterPercent.ValueInt32())
			} else {
				intervalJitterPercent = nil
			}
			noTrafficInterval := new(string)
			if !r.Spec.To[toIndex].Default.NoTrafficInterval.IsUnknown() && !r.Spec.To[toIndex].Default.NoTrafficInterval.IsNull() {
				*noTrafficInterval = r.Spec.To[toIndex].Default.NoTrafficInterval.ValueString()
			} else {
				noTrafficInterval = nil
			}
			reuseConnection := new(bool)
			if !r.Spec.To[toIndex].Default.ReuseConnection.IsUnknown() && !r.Spec.To[toIndex].Default.ReuseConnection.IsNull() {
				*reuseConnection = r.Spec.To[toIndex].Default.ReuseConnection.ValueBool()
			} else {
				reuseConnection = nil
			}
			var tcp *shared.TCP
			if r.Spec.To[toIndex].Default.TCP != nil {
				disabled2 := new(bool)
				if !r.Spec.To[toIndex].Default.TCP.Disabled.IsUnknown() && !r.Spec.To[toIndex].Default.TCP.Disabled.IsNull() {
					*disabled2 = r.Spec.To[toIndex].Default.TCP.Disabled.ValueBool()
				} else {
					disabled2 = nil
				}
				receive := make([]string, 0, len(r.Spec.To[toIndex].Default.TCP.Receive))
				for receiveIndex := range r.Spec.To[toIndex].Default.TCP.Receive {
					receive = append(receive, r.Spec.To[toIndex].Default.TCP.Receive[receiveIndex].ValueString())
				}
				send := new(string)
				if !r.Spec.To[toIndex].Default.TCP.Send.IsUnknown() && !r.Spec.To[toIndex].Default.TCP.Send.IsNull() {
					*send = r.Spec.To[toIndex].Default.TCP.Send.ValueString()
				} else {
					send = nil
				}
				tcp = &shared.TCP{
					Disabled: disabled2,
					Receive:  receive,
					Send:     send,
				}
			}
			timeout := new(string)
			if !r.Spec.To[toIndex].Default.Timeout.IsUnknown() && !r.Spec.To[toIndex].Default.Timeout.IsNull() {
				*timeout = r.Spec.To[toIndex].Default.Timeout.ValueString()
			} else {
				timeout = nil
			}
			unhealthyThreshold := new(int)
			if !r.Spec.To[toIndex].Default.UnhealthyThreshold.IsUnknown() && !r.Spec.To[toIndex].Default.UnhealthyThreshold.IsNull() {
				*unhealthyThreshold = int(r.Spec.To[toIndex].Default.UnhealthyThreshold.ValueInt32())
			} else {
				unhealthyThreshold = nil
			}
			defaultVar = &shared.MeshHealthCheckItemDefault{
				AlwaysLogHealthCheckFailures: alwaysLogHealthCheckFailures,
				EventLogPath:                 eventLogPath,
				FailTrafficOnPanic:           failTrafficOnPanic,
				Grpc:                         grpc,
				HealthyPanicThreshold:        healthyPanicThreshold,
				HealthyThreshold:             healthyThreshold,
				HTTP:                         http,
				InitialJitter:                initialJitter,
				Interval:                     interval,
				IntervalJitter:               intervalJitter,
				IntervalJitterPercent:        intervalJitterPercent,
				NoTrafficInterval:            noTrafficInterval,
				ReuseConnection:              reuseConnection,
				TCP:                          tcp,
				Timeout:                      timeout,
				UnhealthyThreshold:           unhealthyThreshold,
			}
		}
		kind1 := shared.MeshHealthCheckItemSpecKind(r.Spec.To[toIndex].TargetRef.Kind.ValueString())
		labels2 := make(map[string]string)
		for labelsKey1 := range r.Spec.To[toIndex].TargetRef.Labels {
			var labelsInst1 string
			labelsInst1 = r.Spec.To[toIndex].TargetRef.Labels[labelsKey1].ValueString()

			labels2[labelsKey1] = labelsInst1
		}
		mesh2 := new(string)
		if !r.Spec.To[toIndex].TargetRef.Mesh.IsUnknown() && !r.Spec.To[toIndex].TargetRef.Mesh.IsNull() {
			*mesh2 = r.Spec.To[toIndex].TargetRef.Mesh.ValueString()
		} else {
			mesh2 = nil
		}
		name4 := new(string)
		if !r.Spec.To[toIndex].TargetRef.Name.IsUnknown() && !r.Spec.To[toIndex].TargetRef.Name.IsNull() {
			*name4 = r.Spec.To[toIndex].TargetRef.Name.ValueString()
		} else {
			name4 = nil
		}
		namespace1 := new(string)
		if !r.Spec.To[toIndex].TargetRef.Namespace.IsUnknown() && !r.Spec.To[toIndex].TargetRef.Namespace.IsNull() {
			*namespace1 = r.Spec.To[toIndex].TargetRef.Namespace.ValueString()
		} else {
			namespace1 = nil
		}
		proxyTypes1 := make([]shared.MeshHealthCheckItemSpecProxyTypes, 0, len(r.Spec.To[toIndex].TargetRef.ProxyTypes))
		for _, proxyTypesItem1 := range r.Spec.To[toIndex].TargetRef.ProxyTypes {
			proxyTypes1 = append(proxyTypes1, shared.MeshHealthCheckItemSpecProxyTypes(proxyTypesItem1.ValueString()))
		}
		sectionName1 := new(string)
		if !r.Spec.To[toIndex].TargetRef.SectionName.IsUnknown() && !r.Spec.To[toIndex].TargetRef.SectionName.IsNull() {
			*sectionName1 = r.Spec.To[toIndex].TargetRef.SectionName.ValueString()
		} else {
			sectionName1 = nil
		}
		tags1 := make(map[string]string)
		for tagsKey1 := range r.Spec.To[toIndex].TargetRef.Tags {
			var tagsInst1 string
			tagsInst1 = r.Spec.To[toIndex].TargetRef.Tags[tagsKey1].ValueString()

			tags1[tagsKey1] = tagsInst1
		}
		targetRef1 := shared.MeshHealthCheckItemSpecTargetRef{
			Kind:        kind1,
			Labels:      labels2,
			Mesh:        mesh2,
			Name:        name4,
			Namespace:   namespace1,
			ProxyTypes:  proxyTypes1,
			SectionName: sectionName1,
			Tags:        tags1,
		}
		to = append(to, shared.MeshHealthCheckItemTo{
			Default:   defaultVar,
			TargetRef: targetRef1,
		})
	}
	spec := shared.MeshHealthCheckItemSpec{
		TargetRef: targetRef,
		To:        to,
	}
	out := shared.MeshHealthCheckItemInput{
		Type:   typeVar,
		Mesh:   mesh,
		Name:   name,
		Labels: labels,
		Spec:   spec,
	}

	return &out, diags
}
