// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Certificate struct {
	EnvVar         *EnvVar               `tfsdk:"env_var"`
	File           *MeshIdentityItemFile `tfsdk:"file"`
	InsecureInline *InsecureInline       `tfsdk:"insecure_inline"`
	SecretRef      *SecretRef            `tfsdk:"secret_ref"`
	Type           types.String          `tfsdk:"type"`
}
