// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DataplaneOverviewWithMeta struct {
	Dataplane        *Dataplane              `tfsdk:"dataplane"`
	DataplaneInsight *DataplaneInsight       `tfsdk:"dataplane_insight"`
	Labels           map[string]types.String `tfsdk:"labels"`
	Mesh             types.String            `tfsdk:"mesh"`
	Name             types.String            `tfsdk:"name"`
	Type             types.String            `tfsdk:"type"`
}
