// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FromCp struct {
	Address      types.String                         `tfsdk:"address"`
	AgentAddress types.String                         `tfsdk:"agent_address"`
	Auth         *VaultCertificateAuthorityConfigAuth `tfsdk:"auth"`
	CommonName   types.String                         `tfsdk:"common_name"`
	Namespace    types.String                         `tfsdk:"namespace"`
	Pki          types.String                         `tfsdk:"pki"`
	Role         types.String                         `tfsdk:"role"`
	TLS          *VaultCertificateAuthorityConfigTLS  `tfsdk:"tls"`
}
