// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type HashPolicies struct {
	Connection     *Connection  `tfsdk:"connection"`
	Cookie         *Cookie      `tfsdk:"cookie"`
	FilterState    *FilterState `tfsdk:"filter_state"`
	Header         *EnvVar      `tfsdk:"header"`
	QueryParameter *EnvVar      `tfsdk:"query_parameter"`
	Terminal       types.Bool   `tfsdk:"terminal"`
	Type           types.String `tfsdk:"type"`
}
